### ISSUE TITLE
token_already_used? | expected numeric

### ISSUE THREAD

**Issue by williamatodd** [williamatodd/devise-2fa#12]
Version 0.3.0 fails to authenticate OTP after the addition of the token_already_used? method to the flow.

**Comment by williamatodd** [comment]
Version 0.3.0 has been yanked from Rubygems.

**Comment by williamatodd** [comment]
### Parameters

````
{
  "_method": "put",
  "action": "update",
  "authenticity_token": "[FILTERED]",
  "commit": "Submit Token",
  "controller": "devise/credentials",
  "user": {
    "challenge": "[FILTERED]",
    "recovery": "false",
    "token": "[FILTERED]"
  },
  "utf8": "✓"
}
````

### Backtrace
````
activesupport (6.0.0.rc1) lib/active_support/core_ext/date/calculations.rb:104:in `-'
activesupport (6.0.0.rc1) lib/active_support/core_ext/date/calculations.rb:104:in `minus_with_duration'
devise-2fa (bbb3ac5612e5) lib/devise_two_factorable/models/two_factorable.rb:138:in `token_already_used?'
devise-2fa (bbb3ac5612e5) lib/devise_two_factorable/models/two_factorable.rb:124:in `validate_otp_token_with_drift'
devise-2fa (bbb3ac5612e5) lib/devise_two_factorable/models/two_factorable.rb:98:in `validate_otp_time_token'
devise-2fa (bbb3ac5612e5) lib/devise_two_factorable/models/two_factorable.rb:91:in `validate_otp_token'
devise-2fa (bbb3ac5612e5) app/controllers/devise/credentials_controller.rb:45:in `update'
````
